---
name: "Lint"

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Upgrade Setuptools
        run: pip install --upgrade setuptools wheel

      - name: Install requirements
        run: pip install -r requirements-dev.txt

      - name: Run lint
        run: make lint
